### PR TITLE
Template Update

### PR DESCRIPTION
**Pull request by prabinrath**
- Fix the chronology order of the papers. Sequence them from new to old from top to bottom.
- Use pictures from the papers to show in the image placeholders of papers. Videos are already there as youtube links on the old website.
- Paper description is on me. I will write them up once other tasks are done.

### CODE REVIEW

**Comment by prabinrath** [comment]
We will merge this PR once all required changes are completed.

**Comment by NeelamMahapatro** [comment]
@prabinrath , please add description for first 3 publications and merge this PR

**Comment by prabinrath** [comment]
Added missing descriptions. Please make the following changes.
- Separate the projects into two sections Hardware and Software

I will add my new software projects and then merge the PR

**Comment by prabinrath** [comment]
Ready to merge. Thanks, @NeelamMahapatro :+1:  for the help.

**Pull request merged**
